### PR TITLE
Update dependence

### PR DESCRIPTION
**Pull request by KhueHuynh**
Hi Niklas,

I want to update react 15.0.0. Can you review and merge my my commit. It's very useful for new react app.

Thanks, Khue

### CODE REVIEW

**Comment by seadb** [comment]
👍

**Comment by nnarhinen** [comment]
This will make it impossible to use a `File` object as prop?

**Comment by KhueHuynh** [comment]
Hi @nnarhinen ,
I just updated it. Now it can accept string or File as prop.

Thanks, Khue

**Comment by wojtekmaj** [comment]
Closing as react-pdf 1.6.0 is fully updated and this is no longer necessary. Appreciate the help though!

**Pull request closed without merging**
