### PR TITLE
Compatibility update for React 15.x, include pdfjs-dist & introduce linter

### PR DESCRIPTION
**Pull request by wojtekmaj**

### CODE REVIEW

**Comment by nnarhinen** [comment]
Please upgrade minor version and readme if global pdfjs is not needed anymore

**Comment by nnarhinen** [comment]
Can you rebase this PR and I'm happy to merge.

**Comment by wojtekmaj** [comment]
Terribly sorry for the wait, I was super busy!

**Comment by Solitaryo** [comment]
is this working? i'm having the exact same problem with dependencies on react 15

**Comment by wojtekmaj** [comment]
At this point I have no idea. I'm sure though that my fork is working, because I'm using it on a daily basis. I already contacted @nnarhinen offering to take care of this repo but got no answer yet, so if you're struggling with React 15, be my guest ---> https://github.com/wojtekmaj/react-pdf

**Pull request closed without merging**
